# Generated by Django 2.2 on 2019-05-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('headline', models.CharField(blank=True, max_length=300, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
